FROM node:18

WORKDIR /usr/src/app

COPY backend/package*.json ./
RUN npm install --production
COPY backend/ .

# Install PM2 globally
RUN npm install pm2 -g

EXPOSE 5000

CMD ["pm2-runtime", "ecosystem.config.js"]
