version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: fleetlink-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: fleetlink-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: fleetlink-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
